### ISSUE TITLE
Cannot get error information for failed jobs

### ISSUE THREAD

**Issue by simonwo** [filecoin-project/bacalhau#1504]
If I run the command:

    bacalhau docker run busybox "echo bad; exit 2"

I expect the command to error (because non-zero exit code) and to be able to see what the exit code was and what was printed on STDOUT to this effect. However, when I call describe, I get (truncated):

```yaml
Status:
  JobState:
    Nodes:
      QmdZQ7ZbhnvWY1J12XYKGHApJ6aufKyLNSvf8jZBrBaAVL:
        Shards:
          "0":
            NodeId: QmdZQ7ZbhnvWY1J12XYKGHApJ6aufKyLNSvf8jZBrBaAVL
            PublishedResults: {}
            State: Error
            Status: Received ActionComputeError from node QmdZQ7ZbhnvWY1J12XYKGHApJ6aufKyLNSvf8jZBrBaAVL
              that has not bid on this shard
            VerificationResult: {}
  Requester:
    RequesterNodeID: QmYgxZiySj3MRkwLSL4X2MF5F9f2PMhAE3LV49XkfNL1o3
```

Why does it think it has not bid on the shard it has just run?

If I run get:

    Fetching results of job 'c2e730ae-13e1-4c50-bee6-9d6b43a94675'...
    Error: error downloading job: no results found 

This basically means I can't get any error output from a complex task that doesn't return 0.
