### ISSUE TITLE
Submitting a job with a non-existing image name does not return an explicit error message

### ISSUE THREAD

**Issue by enricorotundo** [filecoin-project/bacalhau#1587]
```
❯ bacalhau docker run fooimagename date
Job successfully submitted. Job ID: 0bc272e5-bf90-40ba-87a1-f31e4ef24266
...
	       Creating job for submission ... done ✅
	       Finding node(s) for the job ... done ✅
	             Node accepted the job ... done ✅
	   Error while executing the job.
...
```

```
❯ bacalhau describe 0bc272e5-bf90-40ba-87a1-f31e4ef24266
APIVersion: V1beta1
Metadata:
  ClientID: bae9c3b2adfa04cc647a2457e8c0c605cef8ed93bdea5ac5f19f94219f722dfe
  CreatedAt: "2023-01-04T12:27:50.966161863Z"
  ID: 0bc272e5-bf90-40ba-87a1-f31e4ef24266
...
Status:
  JobState:
    Nodes:
      QmVAb7r2pKWCuyLpYWoZr9syhhFnTWeFaByHdb8PkkhLQG:
        Shards:
          "0":
            NodeId: QmVAb7r2pKWCuyLpYWoZr9syhhFnTWeFaByHdb8PkkhLQG
            PublishedResults: {}
            State: Cancelled
            VerificationResult: {}
      QmXaXu9N5GNetatsvwnTfQqNtSeKAD6uCmarbh3LMRYAcF:
        Shards:
          "0":
            NodeId: QmXaXu9N5GNetatsvwnTfQqNtSeKAD6uCmarbh3LMRYAcF
            PublishedResults: {}
            State: Cancelled
            VerificationResult: {}
      QmYgxZiySj3MRkwLSL4X2MF5F9f2PMhAE3LV49XkfNL1o3:
        Shards:
          "0":
            NodeId: QmYgxZiySj3MRkwLSL4X2MF5F9f2PMhAE3LV49XkfNL1o3
            PublishedResults: {}
            State: Cancelled
            VerificationResult: {}
      QmdZQ7ZbhnvWY1J12XYKGHApJ6aufKyLNSvf8jZBrBaAVL:
        Shards:
          "0":
            NodeId: QmdZQ7ZbhnvWY1J12XYKGHApJ6aufKyLNSvf8jZBrBaAVL
            PublishedResults: {}
            State: Error
            Status: Received ActionComputeError from node QmdZQ7ZbhnvWY1J12XYKGHApJ6aufKyLNSvf8jZBrBaAVL
              that has not bid on this shard
            VerificationResult: {}
...
```

Version `v0.3.16`
