### ISSUE TITLE
Submitting a job with an invalid image name does not return an explicit error message

### ISSUE THREAD

**Issue by enricorotundo** [filecoin-project/bacalhau#1589]
A valid (and accepted) value would be `ubuntu:latest` instead of `ubuntu@latest`.

```
❯ bacalhau docker run ubuntu@latest date
Job successfully submitted. Job ID: 6aaeb63e-c906-49c6-8041-16fde0df4514
Checking job status... (Enter Ctrl+C to exit at any time, your job will continue running):

	       Creating job for submission ... done ✅
	       Finding node(s) for the job ... done ✅
	             Node accepted the job ... done ✅
	   Error while executing the job.

Job Results By Node:

To download the results, execute:
  bacalhau get 6aaeb63e-c906-49c6-8041-16fde0df4514

To get more details about the run, execute:
  bacalhau describe 6aaeb63e-c906-49c6-8041-16fde0df4514
```
```
❯ bacalhau describe 6aaeb63e-c906-49c6-8041-16fde0df4514
APIVersion: V1beta1
Metadata:
  ClientID: bae9c3b2adfa04cc647a2457e8c0c605cef8ed93bdea5ac5f19f94219f722dfe
  CreatedAt: "2023-01-04T13:10:38.015473105Z"
  ID: 6aaeb63e-c906-49c6-8041-16fde0df4514
Spec:
  Deal:
    Concurrency: 1
  Docker:
    Entrypoint:
    - date
    Image: ubuntu@latest
  Engine: Docker
  ExecutionPlan:
    ShardsTotal: 1
  Language:
    JobContext: {}
  Publisher: Estuary
  Resources:
    GPU: ""
  Sharding:
    BatchSize: 1
    GlobPatternBasePath: /inputs
  Timeout: 1800
  Verifier: Noop
  Wasm: {}
  outputs:
  - Name: outputs
    StorageSource: IPFS
    path: /outputs
Status:
  JobState:
    Nodes:
      QmVAb7r2pKWCuyLpYWoZr9syhhFnTWeFaByHdb8PkkhLQG:
        Shards:
          "0":
            NodeId: QmVAb7r2pKWCuyLpYWoZr9syhhFnTWeFaByHdb8PkkhLQG
            PublishedResults: {}
            State: Cancelled
            VerificationResult: {}
      QmXaXu9N5GNetatsvwnTfQqNtSeKAD6uCmarbh3LMRYAcF:
        Shards:
          "0":
            NodeId: QmXaXu9N5GNetatsvwnTfQqNtSeKAD6uCmarbh3LMRYAcF
            PublishedResults: {}
            State: Cancelled
            VerificationResult: {}
      QmYgxZiySj3MRkwLSL4X2MF5F9f2PMhAE3LV49XkfNL1o3:
        Shards:
          "0":
            NodeId: QmYgxZiySj3MRkwLSL4X2MF5F9f2PMhAE3LV49XkfNL1o3
            PublishedResults: {}
            State: Error
            Status: Received ActionComputeError from node QmYgxZiySj3MRkwLSL4X2MF5F9f2PMhAE3LV49XkfNL1o3
              that has not bid on this shard
            VerificationResult: {}
      QmdZQ7ZbhnvWY1J12XYKGHApJ6aufKyLNSvf8jZBrBaAVL:
        Shards:
          "0":
            NodeId: QmdZQ7ZbhnvWY1J12XYKGHApJ6aufKyLNSvf8jZBrBaAVL
            PublishedResults: {}
            State: Cancelled
            VerificationResult: {}
  Requester:
    RequesterNodeID: QmdZQ7ZbhnvWY1J12XYKGHApJ6aufKyLNSvf8jZBrBaAVL
    RequesterPublicKey: CAASpgIwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDVRKPgCfY2fgfrkHkFjeWcqno+MDpmp8DgVaY672BqJl/dZFNU9lBg2P8Znh8OTtHPPBUBk566vU3KchjW7m3uK4OudXrYEfSfEPnCGmL6GuLiZjLf+eXGEez7qPaoYqo06gD8ROdD8VVse27E96LlrpD1xKshHhqQTxKoq1y6Rx4DpbkSt966BumovWJ70w+Nt9ZkPPydRCxVnyWS1khECFQxp5Ep3NbbKtxHNX5HeULzXN5q0EQO39UN6iBhiI34eZkH7PoAm3Vk5xns//FjTAvQw6wZUu8LwvZTaihs+upx2zZysq6CEBKoeNZqed9+Tf+qHow0P5pxmiu+or+DAgMBAAE=
```

Related to https://github.com/filecoin-project/bacalhau/issues/1587

**Comment by enricorotundo** [comment]
This has been fixed already (as of 12368fdd818e579d0cb4f1e1ef6ab87d7e491ea7):

```
❯ go run . docker run bkzzzazzz date
Job successfully submitted. Job ID: aba02e7b-bd4e-4014-bb35-fcceee46bf5d
Checking job status... (Enter Ctrl+C to exit at any time, your job will continue running):

            Communicating with the network  ................ done ✅  0.0s
               Creating job for submission  ................ done ✅  0.0s
               Finding node(s) for the job  ................ done ✅  0.0s
                           Running the job  ................ err  ❌  2.5s

Error while executing the job.
                           Running the job  ................ done ✅  2.5s
```

Check the job status:

```
❯ go run . describe aba02e7b-bd4e-4014-bb35-fcceee46bf5d
...
Status:
  JobState:
    Nodes:
      QmUE87kn414tHfi8CesYoY6tM65pa9SV5UGXh7fjwWL3QA:
        Shards:
          "0":
            ExecutionId: e-62adeb81-0328-4ab2-9a02-ae66b0a658d5
            NodeId: QmUE87kn414tHfi8CesYoY6tM65pa9SV5UGXh7fjwWL3QA
            PublishedResults: {}
            State: Error
            Status: |-
              Could not pull image - could be due to repo/image not existing,
               or registry needing authorization. bkzzzazzz: Error response from daemon: pull access denied for bkzzzazzz, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
            VerificationResult: {}❯ go run . describe aba02e7b-bd4e-4014-bb35-fcceee46bf5d
```
