### ISSUE TITLE
strange error for hello world container

### ISSUE THREAD

**Issue by binocarlos** [filecoin-project/bacalhau#1622]
Running the following docker image locally works:

```
docker run fabriziogianni7/bacalhau-starter:latest python main.py
hello world
```

But trying the same thing on bacalhau gets a strange error:

```
bacalhau docker run fabriziogianni7/bacalhau-starter:latest python main.py
bacalhau describe af963a30-9619-4ecb-9b8b-b7bf8dcd9db6
```

It shows that there is a `compute error`:

```
kai@xwing:~$ bacalhau describe a72e62d8-e6a5-4455-9e39-07ec8914b136
APIVersion: V1beta1
Metadata:
  ClientID: 4ebb7d0e8d891bfac32df0c703b352b787efdca689bb6334edbed91adddeee14
  CreatedAt: "2023-01-10T11:05:36.272049378Z"
  ID: a72e62d8-e6a5-4455-9e39-07ec8914b136
Spec:
  Deal:
    Concurrency: 1
  Docker:
    Entrypoint:
    - python
    - main.py
    Image: fabriziogianni7/bacalhau-starter:latest
  Engine: Docker
  ExecutionPlan:
    ShardsTotal: 1
  Language:
    JobContext: {}
  Publisher: Estuary
  Resources:
    GPU: ""
  Sharding:
    BatchSize: 1
    GlobPatternBasePath: /inputs
  Timeout: 1800
  Verifier: Noop
  Wasm: {}
  outputs:
  - Name: outputs
    StorageSource: IPFS
    path: /outputs
Status:
  JobState:
    Nodes:
      QmVAb7r2pKWCuyLpYWoZr9syhhFnTWeFaByHdb8PkkhLQG:
        Shards:
          "0":
            NodeId: QmVAb7r2pKWCuyLpYWoZr9syhhFnTWeFaByHdb8PkkhLQG
            PublishedResults: {}
            State: Cancelled
            VerificationResult: {}
      QmXaXu9N5GNetatsvwnTfQqNtSeKAD6uCmarbh3LMRYAcF:
        Shards:
          "0":
            NodeId: QmXaXu9N5GNetatsvwnTfQqNtSeKAD6uCmarbh3LMRYAcF
            PublishedResults: {}
            State: Cancelled
            VerificationResult: {}
      QmYgxZiySj3MRkwLSL4X2MF5F9f2PMhAE3LV49XkfNL1o3:
        Shards:
          "0":
            NodeId: QmYgxZiySj3MRkwLSL4X2MF5F9f2PMhAE3LV49XkfNL1o3
            PublishedResults: {}
            State: Error
            Status: Received ActionComputeError from node QmYgxZiySj3MRkwLSL4X2MF5F9f2PMhAE3LV49XkfNL1o3
              that has not bid on this shard
            VerificationResult: {}
      QmdZQ7ZbhnvWY1J12XYKGHApJ6aufKyLNSvf8jZBrBaAVL:
        Shards:
          "0":
            NodeId: QmdZQ7ZbhnvWY1J12XYKGHApJ6aufKyLNSvf8jZBrBaAVL
            PublishedResults: {}
            State: Cancelled
            VerificationResult: {}
```

why is this container erroring when it's running fine locally?
