### ISSUE TITLE
 net/http: TLS handshake timeout in -u

### ISSUE THREAD

**Issue by js-ts** [filecoin-project/bacalhau#477]
2 errors running the same job

<img width="947" alt="image" src="https://user-images.githubusercontent.com/79689323/184323320-3e65ec40-fe4b-4511-8b1c-51da6110b91a.png">

<img width="607" alt="image" src="https://user-images.githubusercontent.com/79689323/184324664-57e70655-8d84-44d7-a08c-963f029ae83f.png">

job.yaml

```
apiVersion: v1alpha1
engine_name: docker
verifier_name: ipfs
job_spec_docker:
  image: ubuntu
  entrypoint:
    - /bin/bash
    - -c
    - mv *.osm.pbf output/
  env: []
resources:
  cpu: ''
  gpu: ''
  memory: ''
  disk: ''
inputs:
  - engine_name: URLDownload
    name: ''
    url: https://download.geofabrik.de/antarctica-latest.osm.pbf
    path: /antarctica-latest.osm.pbf
outputs:
  - engine_name: ipfs
    name: output
    cid: ''
    path: /output
annotations: null
```

**Comment by aronchick** [comment]
@enricorotundo two bugs here - 1) the error is not very clear, 2) any idea on the tls handshake?

**Comment by js-ts** [comment]
the whole dataset

```
apiVersion: v1alpha1
engine_name: docker
verifier_name: ipfs
job_spec_docker:
  image: ubuntu
  entrypoint:
    - /bin/bash
    - -c
    - mv *.osm.pbf output/
  env: []
resources:
  cpu: ''
  gpu: ''
  memory: ''
  disk: ''
inputs:
  - engine_name: URLDownload
    name: ''
    url: https://download.geofabrik.de/africa-latest.osm.pbf
    path: /africa-latest.osm.pbf
  - engine_name: URLDownload
    name: ''
    url: https://download.geofabrik.de/antarctica-latest.osm.pbf
    path: /antarctica-latest.osm.pbf
  - engine_name: URLDownload
    name: ''
    url: https://download.geofabrik.de/asia-latest.osm.pbf
    path: /asia-latest.osm.pbf
  - engine_name: URLDownload
    name: ''
    url: https://download.geofabrik.de/australia-oceania-latest.osm.pbf
    path: /australia-oceania-latest.osm.pbf
  - engine_name: URLDownload
    name: ''
    url: https://download.geofabrik.de/central-america-latest.osm.pbf
    path: /central-america-latest.osm.pbf
  - engine_name: URLDownload
    name: ''
    url: https://download.geofabrik.de/europe-latest.osm.pbf
    path: /europe-latest.osm.pbf
  - engine_name: URLDownload
    name: ''
    url: https://download.geofabrik.de/north-america-latest.osm.pbf
    path: /north-america-latest.osm.pbf
  - engine_name: URLDownload
    name: ''
    url: https://download.geofabrik.de/south-america-latest.osm.pbf
    path: /south-america-latest.osm.pbf
outputs:
  - engine_name: ipfs
    name: output
    cid: ''
    path: /output
annotations: null
```

**Comment by enricorotundo** [comment]
## TLS handshake handshake

Cannot reproduce the error. Works on my local devstack. It's likely a local network,  did you check proxy, ports, etc. on your lan? https://stackoverflow.com/questions/59958274/unable-to-connect-to-the-server-net-http-tls-handshake-timeout

## Error running shard (unclear error)

Somehow the entrypoint `/bin/bash -c mv *.osm.pbf output/` fails without a proper error message. 
The following command works `/bin/bash -c mv *.osm.pbf output/` (see below).
I'll look into adding proper error logging, hopefully that'll shed a light.

```yaml
apiVersion: v1alpha1
engine_name: docker
verifier_name: ipfs
job_spec_docker:
  image: ubuntu
  entrypoint:
    - /bin/bash
    - -c
    - ls -l  *.osm.pbf output/
  env: []
resources:
  cpu: ''
  gpu: ''
  memory: ''
  disk: ''
inputs:
  - engine_name: URLDownload
    name: ''
    url: https://download.geofabrik.de/antarctica-latest.osm.pbf
    path: /antarctica-latest.osm.pbf
outputs:
  - engine_name: ipfs
    name: output
    cid: ''
    path: /output
annotations: null
```

Steps:

```
❯ go run . --api-port=$BACALHAU_API_PORT_0 --api-host=localhost \
    apply -f job.yaml
b5e8f3e8-df6c-42f2-b03d-2fedb6e27d15

❯ go run . --api-port=$BACALHAU_API_PORT_0 --api-host=localhost list --wide
 CREATION_TIME      ID                                    JOB                                                          STATE     RESULT                                               
 22-08-15-12:38:56  b5e8f3e8-df6c-42f2-b03d-2fedb6e27d15  Docker ubuntu /bin/bash -c ls -l /antarctica-latest.osm.pbf  Complete  /ipfs/QmT8dPkRUaGYGnxKx9myvYQuJydB7nzUcALyRiRKiYCHEa 

❯ ipfs --api /ip4/127.0.0.1/tcp/${BACALHAU_IPFS_API_PORT_0} cat $RESULT_PATH/stdout
-rw-r--r-- 1 root root 32519437 Aug 15 10:38 /antarctica-latest.osm.pbf
```

@js-ts
