### ISSUE TITLE
DevStack not able to debug HTTP URLs

### ISSUE THREAD

**Issue by aronchick** [filecoin-project/bacalhau#478]
Applying a job like this against devstack:
```
apiVersion: v1alpha1
engine_name: docker
verifier_name: ipfs
job_spec_docker:
  image: ubuntu
  entrypoint:
    - /bin/bash
    - -c
    - mv *.osm.pbf output/
  env: []
resources:
  cpu: ''
  gpu: ''
  memory: ''
  disk: ''
inputs:
  - engine_name: URLDownload
    name: ''
    url: https://download.geofabrik.de/antarctica-latest.osm.pbf
    path: /antarctica-latest.osm.pbf
outputs:
  - engine_name: ipfs
    name: output
    cid: ''
    path: /output
annotations: null
```

Which is a well formed URL, we get the following results:
```
[2207] INF computenode/job_selection.go:147 > Found 0 of 1 inputs - passing on job
[2207] DBG computenode/computenode.go:393 > Compute node QmNUKEtoovxW74Lb4Tkv5UMNADe5uhs98qaewfeDBAPSqb skipped bidding on job because policy did not pass: bfcebe71-1612-4393-bfc8-7ce5fd99d22d
[2207] INF computenode/job_selection.go:147 > Found 0 of 1 inputs - passing on job
[2207] DBG computenode/computenode.go:393 > Compute node QmPJna7zhVWNb1KWBJQGMsJBy48yfyjLwsGvTpJcTdz8St skipped bidding on job because policy did not pass: bfcebe71-1612-4393-bfc8-7ce5fd99d22d
[2207] INF computenode/job_selection.go:147 > Found 0 of 1 inputs - passing on job
[2207] DBG computenode/computenode.go:393 > Compute node QmReAigoNkw4uag8EUgYHDUcNpQCFaitsqLkJBbyQDkmyX skipped bidding on job because policy did not pass: bfcebe71-1612-4393-bfc8-7ce5fd99d22d
```

All three nodes passed on bidding. The reason they all pass is because of this line:
https://github.com/filecoin-project/bacalhau/blob/main/pkg/executor/docker/executor.go#L92

Which in devstack fails to result in local storage. Not sure what we should do about this! E.g. should we create temp storage/storage provider for devstack?
