### ISSUE TITLE
Need to significantly improve error reports

### ISSUE THREAD

**Issue by aronchick** [filecoin-project/bacalhau#591]
This is pretty unclear....

```
❯ bacalhau describe 3dcee2a0
Id: 3dcee2a0-c090-4270-88c2-3abc25ac8d83
ClientID: d4d4e28b7683be4a30d86b6eaf733fcf5b13de9a0a38d7247d0a020d27483771
RequesterNodeId: QmdZQ7ZbhnvWY1J12XYKGHApJ6aufKyLNSvf8jZBrBaAVL
Spec:
    Engine: Docker
    Verifier: Noop
    Docker:
        Image: bacalhauproject/dataprocessing-splitfile
        Entrypoint Command: []
        Submitted Env Variables:
            - FILE_TO_PROCESS=/inputs/sample_set.csv
        CPU Allocated: ""
        Memory Allocated: ""
        Inputs: []
        Outputs: []
        Annotations: []
    Deployment:
        Concurrency: 0
        Confidence: 0
        Assigned Nodes: []
Deal:
    concurrency: 1
    confidence: 0
    minbids: 0
Shards:
    - ShardIndex: 0
      Nodes:
        - Node: QmdZQ7ZbhnvWY1J12XYKGHApJ6aufKyLNSvf8jZBrBaAVL
          State: Error
          Status: '[QmdZQ7Zb] shard: 3dcee2a0-c090-4270-88c2-3abc25ac8d83:0 at state: Error error completing job due to exit code was not zero: 1'
          Verified: false
          ResultID: ""
        - Node: QmXaXu9N5GNetatsvwnTfQqNtSeKAD6uCmarbh3LMRYAcF
          State: Cancelled
          Status: ""
          Verified: false
          ResultID: ""
Start Time: 2022-09-09T21:58:36.797144855Z
Events:
    - Event: Created
      Time: 2022-09-09 21:58:36.797005515 +0000 UTC
      Concurrency: 1
      Confidence: 0
      SourceNode: QmdZQ7ZbhnvWY1J12XYKGHApJ6aufKyLNSvf8jZBrBaAVL
      TargetNode: ""
      Status: ""
    - Event: Bid
      Time: 2022-09-09 21:58:36.89010825 +0000 UTC
      Concurrency: 0
      Confidence: 0
      SourceNode: QmdZQ7ZbhnvWY1J12XYKGHApJ6aufKyLNSvf8jZBrBaAVL
      TargetNode: ""
      Status: ""
    - Event: Bid
      Time: 2022-09-09 21:58:36.90072298 +0000 UTC
      Concurrency: 0
      Confidence: 0
      SourceNode: QmXaXu9N5GNetatsvwnTfQqNtSeKAD6uCmarbh3LMRYAcF
      TargetNode: ""
      Status: ""
    - Event: BidAccepted
      Time: 2022-09-09 21:58:36.907185259 +0000 UTC
      Concurrency: 0
      Confidence: 0
      SourceNode: QmdZQ7ZbhnvWY1J12XYKGHApJ6aufKyLNSvf8jZBrBaAVL
      TargetNode: QmdZQ7ZbhnvWY1J12XYKGHApJ6aufKyLNSvf8jZBrBaAVL
      Status: ""
    - Event: BidRejected
      Time: 2022-09-09 21:58:36.921166976 +0000 UTC
      Concurrency: 0
      Confidence: 0
      SourceNode: QmdZQ7ZbhnvWY1J12XYKGHApJ6aufKyLNSvf8jZBrBaAVL
      TargetNode: QmXaXu9N5GNetatsvwnTfQqNtSeKAD6uCmarbh3LMRYAcF
      Status: ""
    - Event: Error
      Time: 2022-09-09 21:58:42.905950166 +0000 UTC
      Concurrency: 0
      Confidence: 0
      SourceNode: QmdZQ7ZbhnvWY1J12XYKGHApJ6aufKyLNSvf8jZBrBaAVL
      TargetNode: ""
      Status: '[QmdZQ7Zb] shard: 3dcee2a0-c090-4270-88c2-3abc25ac8d83:0 at state: Error error completing job due to exit code was not zero: 1'
LocalEvents:
    - Event: Selected
      TargetNode: ""
    - Event: Bid
      TargetNode: ""
    - Event: BidAccepted
      TargetNode: QmdZQ7ZbhnvWY1J12XYKGHApJ6aufKyLNSvf8jZBrBaAVL
    - Event: BidRejected
      TargetNode: QmXaXu9N5GNetatsvwnTfQqNtSeKAD6uCmarbh3LMRYAcF
    - Event: Verified
      TargetNode: ""
```

Job ran fine locally, in the docker image.
