### ISSUE TITLE
ShardState should be rendered as an Enum

### ISSUE THREAD

**Issue by aronchick** [filecoin-project/bacalhau#835]
```
      Shards:
        "0":
          NodeId: QmYgxZiySj3MRkwLSL4X2MF5F9f2PMhAE3LV49XkfNL1o3
          PublishedResults: {}
          RunOutput:
            exitCode: 0
            runnerError: 'error pulling echo: exit status 1, '
            stderr: ""
            stderrtruncated: false
            stdout: ""
            stdouttruncated: false
          State: 6
```
